# config.yaml

devices:
  # --- Robots ---
  mirror_robot:
    type: "mecademic"
    ip_address: "192.168.0.101"

  dispenser_robot:
    type: "mecademic"
    ip_address: "192.168.0.102"
    
  # --- Accessories/Controllers ---

  arduino_io:
    type: "arduino"
    port: "COM3"
